"""auto write hierarchical planner tables

Revision ID: 0521db79b091
Revises: c4a1c9bbe030
Create Date: 2026-09-09 23:00:33.449303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0521db79b091'
down_revision: Union[str, None] = 'c4a1c9bbe030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_write_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_episode', sa.Integer(), nullable=False),
    sa.Column('end_episode', sa.Integer(), nullable=False),
    sa.Column('current_episode', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('writer_model', sa.String(length=150), nullable=False),
    sa.Column('controller_model', sa.String(length=150), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('arc_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_plan_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('arc_number', sa.Integer(), nullable=False),
    sa.Column('start_episode', sa.Integer(), nullable=False),
    sa.Column('end_episode', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_plan_id'], ['series_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mini_arc_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arc_plan_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('mini_arc_number', sa.Integer(), nullable=False),
    sa.Column('start_episode', sa.Integer(), nullable=False),
    sa.Column('end_episode', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['arc_plan_id'], ['arc_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mini_arc_plan_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['mini_arc_plan_id'], ['mini_arc_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode_plans')
    op.drop_table('mini_arc_plans')
    op.drop_table('arc_plans')
    op.drop_table('series_plans')
    op.drop_table('auto_write_jobs')
    # ### end Alembic commands ###
