"""add project episode_goal

Revision ID: 07aeee4090a2
Revises: 0521db79b091
Create Date: 2026-09-10 00:15:23.969782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07aeee4090a2'
down_revision: Union[str, None] = '0521db79b091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('episode_goal', sa.Integer(), nullable=False, server_default='500'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'episode_goal')
    # ### end Alembic commands ###
