"""add import jobs table

Revision ID: 1164a31f3283
Revises: 9c60773d90c4
Create Date: 2026-09-10 19:54:12.076931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1164a31f3283'
down_revision: Union[str, None] = '9c60773d90c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('source_filename', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=False),
    sa.Column('processed_episodes', sa.Integer(), nullable=False),
    sa.Column('created_episodes', sa.Integer(), nullable=False),
    sa.Column('updated_episodes', sa.Integer(), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_project_id'), 'import_jobs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_jobs_project_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
