"""add episode revisions and planner indexes

Revision ID: 3bbe0be6549d
Revises: 07aeee4090a2
Create Date: 2026-09-10 06:31:08.405416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbe0be6549d'
down_revision: Union[str, None] = '07aeee4090a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_revisions_episode_id'), 'episode_revisions', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_revisions_project_id'), 'episode_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_arc_plans_project_id'), 'arc_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_arc_plans_series_plan_id'), 'arc_plans', ['series_plan_id'], unique=False)
    op.create_index(op.f('ix_auto_write_jobs_project_id'), 'auto_write_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_episode_plans_mini_arc_plan_id'), 'episode_plans', ['mini_arc_plan_id'], unique=False)
    op.create_index(op.f('ix_episode_plans_project_id'), 'episode_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_mini_arc_plans_arc_plan_id'), 'mini_arc_plans', ['arc_plan_id'], unique=False)
    op.create_index(op.f('ix_mini_arc_plans_project_id'), 'mini_arc_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_series_plans_project_id'), 'series_plans', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_plans_project_id'), table_name='series_plans')
    op.drop_index(op.f('ix_mini_arc_plans_project_id'), table_name='mini_arc_plans')
    op.drop_index(op.f('ix_mini_arc_plans_arc_plan_id'), table_name='mini_arc_plans')
    op.drop_index(op.f('ix_episode_plans_project_id'), table_name='episode_plans')
    op.drop_index(op.f('ix_episode_plans_mini_arc_plan_id'), table_name='episode_plans')
    op.drop_index(op.f('ix_auto_write_jobs_project_id'), table_name='auto_write_jobs')
    op.drop_index(op.f('ix_arc_plans_series_plan_id'), table_name='arc_plans')
    op.drop_index(op.f('ix_arc_plans_project_id'), table_name='arc_plans')
    op.drop_index(op.f('ix_episode_revisions_project_id'), table_name='episode_revisions')
    op.drop_index(op.f('ix_episode_revisions_episode_id'), table_name='episode_revisions')
    op.drop_table('episode_revisions')
    # ### end Alembic commands ###
