"""add runtime_config table

Revision ID: 9c60773d90c4
Revises: a255e0bcc2f7
Create Date: 2026-09-10 18:05:44.430741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c60773d90c4'
down_revision: Union[str, None] = 'a255e0bcc2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qdrant_url', sa.String(length=500), nullable=True),
    sa.Column('ollama_url', sa.String(length=500), nullable=True),
    sa.Column('ollama_model', sa.String(length=150), nullable=True),
    sa.Column('ollama_embed_model', sa.String(length=150), nullable=True),
    sa.Column('controller_ollama_url', sa.String(length=500), nullable=True),
    sa.Column('controller_ollama_model', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_config')
    # ### end Alembic commands ###
